eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
logging:
    config: classpath:logback-spring.xml
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.imcp.basic.bean
server:
    port: 2010
spring:
    application:
        name: IMCP-BASIC
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/imcp_basic?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
        username: root
